INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ANOTHERTUTORIAL anothertutorial)

FIND_PATH(
    ANOTHERTUTORIAL_INCLUDE_DIRS
    NAMES anothertutorial/api.h
    HINTS $ENV{ANOTHERTUTORIAL_DIR}/include
        ${PC_ANOTHERTUTORIAL_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ANOTHERTUTORIAL_LIBRARIES
    NAMES gnuradio-anothertutorial
    HINTS $ENV{ANOTHERTUTORIAL_DIR}/lib
        ${PC_ANOTHERTUTORIAL_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ANOTHERTUTORIAL DEFAULT_MSG ANOTHERTUTORIAL_LIBRARIES ANOTHERTUTORIAL_INCLUDE_DIRS)
MARK_AS_ADVANCED(ANOTHERTUTORIAL_LIBRARIES ANOTHERTUTORIAL_INCLUDE_DIRS)

